language: r
sudo: false
cache: packages
dist: focal
r:
  - release

addons:
  apt:
    packages:
      - libgsl0-dev

env:
  global:
    - _R_CHECK_TIMINGS_=0
    - _R_CHECK_FORCE_SUGGESTS_=false  # no error if suggested packs are not avail
    - _R_CHECK_TESTS_NLINES_=999
    - NOT_CRAN=false

warnings_are_errors: true
r_check_args: "--as-cran --run-donttest"

before_install:
  # we want to see libpaths and installed packages from cache
  - Rscript -e 'message("LIBPATHS:"); .libPaths()'
  - Rscript -e 'message("INSTALLED PACKS:"); installed.packages()[,2:3]'

before_script:
  - rm inst/doc/*.* || true
  - Rscript -e 'if (!require("roxygen2")) install.packages("roxygen2")'
  - Rscript -e 'if (!require("pkgdown")) install.packages("pkgdown")'
  - Rscript -e 'if (!require("covr")) install.packages("covr")'
  - Rscript -e 'roxygen2::roxygenise()'

after_failure:
  - ./travis-tool.sh dump_logs

script:
  # github mlr & tools
  - Rscript -e 'message("INSTALLED PACKS:"); installed.packages()[,2:3]'
  - R CMD build .
  - travis_wait 100 R CMD check mlrintermbo*.tar.gz --as-cran --run-donttest
  - grep -q -R "WARNING" "mlrintermbo.Rcheck/00check.log" ; [ $? -ne 0 ]
after_success:
  - travis_wait 100 Rscript -e 'covr::codecov(quiet=FALSE)'
before_deploy:
  - R CMD INSTALL mlrintermbo*.tar.gz
  - Rscript -e 'pkgdown::build_site(); roxygen2::roxygenise(); tools::buildVignettes(dir = ".");'
  - mv vignettes/*.html inst/doc || true
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: docs
  on:
    branch: master
after_deploy:
  - git checkout master  # otherwise we're in detached head
  - "export TRAVIS_COMMIT_MSG=\"$(git log --format=%B --no-merges -n 1)\""
  - git config user.name Travis
  - git config user.email '<>'
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GITHUB_TOKEN}:@github.com" >> .git/credentials
  - git config push.default matching
  - |
    git difftool -yx "diff -qI '20[0-9][0-9]-[0-9][0-9]-[0-9][0-9]\\\\|environment. 0x\\\\|time. [0-9.]\\\\+'" | \
    grep 'and inst/doc' | sed -e 's|.*and inst/doc|inst/doc|' -e 's/ differ$//' | xargs git add
  - git add --force man/*
  - git add DESCRIPTION NAMESPACE
  - git commit -m "update auto-generated documentation [ci skip]" || true
  - git push
      
on_success: change
on_failure: always

notifications:
  email: false
